Support for docker --build-arg
sebastianseilund/orca pull request #2
Opened 2017-04-06 13:42 UTC by fiolkaf

It will be so cool if orca supports docker build-args.

We use it to pass NPM credentials, so we can fetch from private repositories on docker build.
But it could be used for anything - HTTP_PROXY, private RubyGems creds, etc.

Sky is the limit ;-)

2017-04-06 15:25 UTC, sebastianseilund commented
Sounds like a good idea :)

Could you rename `env` to `buildArgs` all the way through? I think that's more appropriate as that's where the arguments go. Other than that everything is 👍

2017-05-16 08:16 UTC, fiolkaf commented
@sebastianseilund: are you good with it ?

2017-05-16 18:17 UTC, sebastianseilund requested changes

2017-05-16 18:17 UTC, sebastianseilund commented on src/watcher.js
> +                params.push(`${key}="${value}"`)
Just realized that there's a risk of including bad unescaped arguments here. Can you escape both the key and the value? There must be a module for that you can use.

2017-05-17 08:15 UTC, fiolkaf commented on src/watcher.js
> +                params.push(`${key}="${value}"`)
good point, already implemented.

2017-05-19 08:04 UTC, merged

2017-05-19 08:05 UTC, sebastianseilund commented
Thanks!